<?php

namespace AppBundle\Repository;

/**
 * PosteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostesByGroupId($groupId)
    {
        return $this->createQueryBuilder('p')
            ->where('p.group = :group')
            ->orWhere('p.createdByGroup = :group')
            ->setParameter('group', $groupId)
            ->getQuery()
            ->getResult();
    }
}
