<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Candidature;
use AppBundle\Entity\Poste;
use AppBundle\Entity\Profile;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($disp, $exper, $sivp, $comp)
    {
        return $this->_em->getRepository(Candidature::class)->createQueryBuilder('c')
            ->select('c, p, post')
            ->join('c.profile', 'p')
            ->join('c.poste', 'post')
            ->where('p.disponibilite =: disp')
            ->andWhere('p.experience =:expr')
            ->andWhere('p.sivp =:sivp')
            ->andWhere('p.competence =:compt')
            ->setParameter('disp', $disp)
            ->setParameter('expr', $exper)
            ->setParameter('sivp', $sivp)
            ->setParameter('compt', $comp)
//            ->andWhere('post. =:')
//            ->getQuery('post.')
            ->getFirstResult();
    }
}
