# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.rapport_listener:
        class: AppBundle\Entity\Listeners\RapportListener
        tag:
            - { name: doctrine.orm.entity_listener }
    app.candidature_service:
        class: AppBundle\Service\CompetenceService
        arguments: [ "@doctrine.orm.entity_manager" ]
