parameters:
    database_manager.candidature.class: AppBundle\ModelManager\CandidatureManager
    database_manager.etape.class: AppBundle\ModelManager\EtapeManager
    database_manager.poste.class: AppBundle\ModelManager\PosteManager
    database_manager.profile.class: AppBundle\ModelManager\ProfileManager

services:
    app.rapport_listener:
        class: AppBundle\Entity\Listeners\RapportListener
        tag:
            - { name: doctrine.orm.entity_listener }
    app.poste_listener:
        class: AppBundle\Entity\Listeners\PosteListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.orm.entity_listener }
    app.candidature_service:
        class: AppBundle\Service\CompetenceService
        arguments: [ "@doctrine.orm.entity_manager" ]
    app.profile_service:
        class: AppBundle\Service\SearchService
        arguments: [ "@doctrine.orm.entity_manager" ]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    model_manager.candidature:
        class: '%database_manager.candidature.class%'
        arguments: [ "@doctrine", "@form.factory", "@router", "@request_stack"]
    model_manager.etape:
            class: '%database_manager.etape.class%'
            arguments: [ "@doctrine"]
    model_manager.poste:
            class: '%database_manager.poste.class%'
            arguments: [ "@doctrine"]
    model_manager.profile:
            class: '%database_manager.profile.class%'
            arguments: [ "@doctrine"]
