# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.rapport_listener:
        class: AppBundle\Entity\Listeners\RapportListener
        tag:
            - { name: doctrine.orm.entity_listener }
    app.poste_listener:
        class: AppBundle\Entity\Listeners\PosteListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.orm.entity_listener }
    app.candidature_service:
        class: AppBundle\Service\CompetenceService
        arguments: [ "@doctrine.orm.entity_manager" ]
    app.profile_service:
        class: AppBundle\Service\SearchService
        arguments: [ "@doctrine.orm.entity_manager" ]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }