<?php

namespace AppBundle;

/**
 * RepositoryNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
